version: "3"
services:
  app:
    build: .
    container_name: smartchainops_app
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    command: ["node", "backend/server.js"]
    volumes:
      - .:/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
