pipeline {
    agent any

    environment {
        MONGO_URI="mongodb+srv://suyashgupta2411:pu7GqVJr1DGpgR9e@cluster0.co3aj.mongodb.net/smartchainops?retryWrites=true&w=majority&appName=Cluster0"
        JWT_SECRET="5e4c8615ad98bc421342f5d1f0de1839649ba5dbaf336767fbcf35c342efaa04ae88db5b77aeb1395073d08876753206098695d909b9813302b2ce3d3c96c7aa"


        DOCKER_IMAGE = "suyashgupta1/SmartChainOps" 
        GITHUB_REPO_URL = "https://github.com/suyashgupta2411/SmartChainOps.git" 
    }

    stages {
        stage('Clone Repository') {
            steps {
                // Clone the GitHub repository
                git branch: 'main', url: "${GITHUB_REPO_URL}"
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    // Build Docker image
                    sh 'docker build -t ${DOCKER_IMAGE} .'
                }
            }
        }
        stage('Run Docker Container') {
            steps {
                script {
                    // Run Docker container
                    sh 'docker run -d -p 5000:5000 --name smartchainops-backend ${DOCKER_IMAGE}'
                }
            }
        }
    }

    post {
        always {
            // Cleanup Docker containers and images after the build
            script {
                sh 'docker stop smartchainops-backend || true'
                sh 'docker rm smartchainops-backend || true'
                sh 'docker rmi ${DOCKER_IMAGE} || true'
            }
        }
    }
}
